export const COSMETICSPRODUCTS = [
  {
    id: 1,
    name: "Cell Fusion C Advanced Clear Sunscreen SPF 50+",
    img: "/items/Cosmetics/CellFusionC]AdvancedClearSunscreenSPF50+.jpg",
    price: 10.3,
  },
  {
    id: 2,
    name: "Cell Fusion C Aquatica Stick Sunscreen 100 SPF 50+",
    img: "/items/Cosmetics/CellFusionC]AquaticaStickSunscreen100SPF50+.jpg",
    price: 10.5,
  },
  {
    id: 3,
    name: "Cell Fusion C Aquatica Sunscreen SPF 50+",
    img: "/items/Cosmetics/CellFusionC]AquaticaSunscreenSPF50+.jpg",
    price: 12.2,
  },
  {
    id: 4,
    name: "Cell Fusion C Derma Relief Sunscreen SPF 50+",
    img: "/items/Cosmetics/CellFusionC]DermaReliefSunscreenSPF50+.jpg",
    price: 13.1,
  },
  {
    id: 5,
    name: "Cell Fusion C Laser Sunscreen SPF 50+",
    img: "/items/Cosmetics/CellFusionC]LaserSunscreenSPF50+.jpg",
    price: 14.1,
  },
  {
    id: 6,
    name: "Cell Fusion C Toning C Dark Spot Serum",
    img: "/items/Cosmetics/CellFusionC]ToningCDarkSpotSerum.jpg",
    price: 11.5,
  },
  {
    id: 7,
    name: "Cell Fusion C Toning Sunscreen SPF 50+",
    img: "/items/Cosmetics/CellFusionC]ToningSunscreenSPF50+.jpg",
    price: 15.1,
  },
  {
    id: 8,
    name: "d'Alba sunscreen",
    img: "/items/Cosmetics/dAlbasunscreen.jpg",
    price: 13,
  },
  {
    id: 9,
    name: "d'Alba White Truffle First Aromatic Spray Serum",
    img: "/items/Cosmetics/dAlbaWhiteTruffleFirstAromaticSpraySerum.jpg",
    price: 10,
  },
  {
    id: 10,
    name: "Dr G Brightening Peeling Gel",
    img: "/items/Cosmetics/Dr.GBrighteningPeelingGel.jpg",
    price: 19.1,
  },
  {
    id: 11,
    name: "Dr G Brightening Up Sun+ SPF50+ PA+++",
    img: "/items/Cosmetics/Dr.GBrighteningUpSun+SPF50+PA+++.jpg",
    price: 9.1,
  },
  {
    id: 12,
    name: "Dr G Green Mild Up Sun+ SPF50+ PA++++",
    img: "/items/Cosmetics/Dr.GGreenMildUpSun+SPF50+PA++++.jpeg",
    price: 11.9,
  },
  {
    id: 13,
    name: "Dr G Red Blemish Clear Soothing Cream 70ml",
    img: "/items/Cosmetics/Dr.GRedBlemishClearSoothingCream70ml.jpg",
    price: 12,
  },
  {
    id: 14,
    name: "Dr G Black Snail Cream",
    img: "/items/Cosmetics/DrGBlackSnailCream.jpg",
    price: 13.2,
  },
  {
    id: 15,
    name: "Goodal Vita C Serum",
    img: "/items/Cosmetics/GoodalVitaCSerum.jpg",
    price: 9,
  },
  {
    id: 16,
    name: "Innisfree Hyaluron Moist Sunscreen 50mL",
    img: "/items/Cosmetics/InnisfreeHyaluronMoistSunscreen50mL.jpg",
    price: 7.1,
  },
  {
    id: 17,
    name: "Innisfree Intensive Long Lasting Sunscreen EX60m",
    img: "/items/Cosmetics/InnisfreeIntensiveLongLastingSunscreenEX60m.jpg",
    price: 6.4,
  },
  {
    id: 18,
    name: "Innisfree Peeling Mask",
    img: "/items/Cosmetics/InnisfreePeelingMask.jpg",
    price: 16.1,
  },
  {
    id: 19,
    name: "Innisfree Tone Up No Sebum Sunscreen EX60ml",
    img: "/items/Cosmetics/InnisfreeToneUpNoSebumSunscreenEX60ml.jpg",
    price: 17.4,
  },
  {
    id: 20,
    name: "Innisfree UV Active Poreless Sunscreen 50ml",
    img: "/items/Cosmetics/InnisfreeUVActivePorelessSunscreen50ml.jpg",
    price: 16.5,
  },
  {
    id: 21,
    name: "JAYJUN Black Mask",
    img: "/items/Cosmetics/JAYJUNBlackMask.jpg",
    price: 12.8,
  },
  {
    id: 22,
    name: "JAYJUN Real Water Brightening Black Hydro Sleeping Mask",
    img: "/items/Cosmetics/JAYJUNRealWaterBrighteningBlackHydroSleepingMask.png",
    price: 11,
  },
  {
    id: 23,
    name: "JM Solution Active Pink Snail Brightening Mask",
    img: "/items/Cosmetics/JMSolutionActivePinkSnailBrighteningMask.jpg",
    price: 16.8,
  },
  {
    id: 24,
    name: "JM Solution Marine Luminous Pearl Sun Protection Sun Spray",
    img: "/items/Cosmetics/JMSolutionMarineLuminousPearlSunProtectionSunSpray.jpg",
    price: 11.3,
  },
  {
    id: 25,
    name: "Ohuicushion",
    img: "/items/Cosmetics/Ohuicushion.jpg",
    price: 25,
  },
];
