export const GINSENGPRODUCTS = [
  {
    id: 46,
    name: "an cung sam sung",
    img: "/items/Ginseng/ancungsamsung.jpg",
    price: 54.1,
  },
  // {
  //   id: 47,
  //   name: "an cung sam sung 1",
  //   img: "/items/Ginseng/ancungsamsung1.jpg",
  //   price: 54.1,
  // },
  {
    id: 48,
    name: "bo gan",
    img: "/items/Ginseng/bogan.jpg",
    price: 42.3,
  },
  // {
  //   id: 49,
  //   name: "bo gan 1",
  //   img: "/items/Ginseng/bogan1.jpg",
  //   price: 42.3,
  // },
  // {
  //   id: 50,
  //   name: "bo gan 2",
  //   img: "/items/Ginseng/bogan2.png",
  //   price: 42.3,
  // },
  {
    id: 51,
    name: "kickergold",
    img: "/items/Ginseng/kickergold.jpg",
    price: 32.5,
  },
  // {
  //   id: 52,
  //   name: "kickergold 1",
  //   img: "/items/Ginseng/kickergold1.jpg",
  //   price: 32.5,
  // },
  // {
  //   id: 53,
  //   name: "kickergold 2",
  //   img: "/items/Ginseng/kickergold2.jpg",
  //   price: 32.5,
  // },
  {
    id: 54,
    name: "Lactofit",
    img: "/items/Ginseng/Lactofit.jpg",
    price: 28.2,
  },
  {
    id: 55,
    name: "nam 1",
    img: "/items/Ginseng/nam1.jpg",
    price: 61,
  },
  // {
  //   id: 56,
  //   name: "nam 2",
  //   img: "/items/Ginseng/nam2.jpg",
  //   price: 61,
  // },
  {
    id: 57,
    name: "sam 1",
    img: "/items/Ginseng/sam1.jpg",
    price: 41,
  },
  // {
  //   id: 58,
  //   name: "sam 2",
  //   img: "/items/Ginseng/sam2.jpg",
  //   price: 23,
  // },
  // {
  //   id: 59,
  //   name: "sam 3",
  //   img: "/items/Ginseng/sam3.jpg",
  //   price: 45,
  // },
  // {
  //   id: 60,
  //   name: "sam 4",
  //   img: "/items/Ginseng/sam4.jpg",
  //   price: 43,
  // },
  // {
  //   id: 61,
  //   name: "sam 5",
  //   img: "/items/Ginseng/sam5.jpg",
  //   price: 63.2,
  // },
  {
    id: 62,
    name: "sam kho",
    img: "/items/Ginseng/samkho.jpg",
    price: 41.3,
  },
  {
    id: 63,
    name: "thachhongsam",
    img: "/items/Ginseng/thachhongsam.jpg",
    price: 31,
  },
  // {
  //   id: 64,
  //   name: "thachhongsam 1",
  //   img: "/items/Ginseng/thachhongsam1.jpg",
  //   price: 40.2,
  // },
  // {
  //   id: 65,
  //   name: "thachhongsam 2",
  //   img: "/items/Ginseng/thachhongsam2.jpg",
  //   price: 47.1,
  // },
];
